//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceCare.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public Invitation()
        {
            this.InvitationRoles = new HashSet<InvitationRole>();
        }
    
        public int Id { get; set; }
        public string Token { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UsedOn { get; set; }
        public string UserId { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<InvitationRole> InvitationRoles { get; set; }
    }
}
