//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceCare.Central
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestAccess
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Reason { get; set; }
        public System.DateTime Date { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> DateStatusChanged { get; set; }
        public string UserStatusChanged { get; set; }
    }
}
